name: Helm Chart CI

on:
  push:
    paths:
      - 'charts/**'
    branches:
      - main
  repository_dispatch:
    types: [trigger-helm-build]

jobs:
  helm-chart-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Update Helm Chart Version
        run: |
          cd charts/terraflaskqlk8s-chart
          sed -i "s/version: .*/version: 0.0.${{ github.run_number }}/g" Chart.yaml
          echo "# Auto-updated by CI workflow" >> Chart.yaml

      - name: Package Helm Chart
        run: |
          cd charts
          helm package terraflaskqlk8s-chart --destination ..
          cd ..
          ls -lrta

      - name: Update Helm Repo Index
        run: |
          helm repo index --url https://yuvalbenar.github.io/helm-charts/ .  # Ensure the index URL matches the GitHub Pages URL
          ls -lrta

      - name: Move Helm Chart and Index to docs Directory
        run: |
          # Move the .tgz files and index.yaml into the docs directory for GitHub Pages
          mkdir -p docs
          mv *.tgz docs/
          mv index.yaml docs/
          ls -lrta docs/

      - name: Push Helm Chart to Repository
        env:
          HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "github-actions@github.com"

          git add docs/*
          git commit -m "Updated Helm charts and index.yaml"
          git push origin main

          echo "Helm chart successfully updated in /docs!"
